// The terminal the runner photographs and records: xterm.js (ttyd's front end)
// in the devtools scheme, the same one every terminal on the site draws, so a
// screenshot, a recording and the page around them are one set of colours.
//
// The shell draws in palette slots (the sixteen ANSI names), never hex: a
// recording is played back in whatever scheme the site uses, and a prompt in
// slots follows it where one in hex would carry these colours into every
// theme.

import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

export async function loadScheme(site) {
	const { devtools } = await import(
		pathToFileURL(path.join(site, 'src/lib/terminal/scheme.js')).href
	);
	return devtools;
}

// xterm.js theme, from a scheme.
export function xtermTheme(s) {
	const p = s.palette;
	return {
		background: s.background,
		foreground: s.foreground,
		cursor: s.cursor,
		cursorAccent: s.cursorText,
		selectionBackground: s.selection,
		selectionForeground: s.selectionText,
		black: p[0],
		red: p[1],
		green: p[2],
		yellow: p[3],
		blue: p[4],
		magenta: p[5],
		cyan: p[6],
		white: p[7],
		brightBlack: p[8],
		brightRed: p[9],
		brightGreen: p[10],
		brightYellow: p[11],
		brightBlue: p[12],
		brightMagenta: p[13],
		brightCyan: p[14],
		brightWhite: p[15]
	};
}

// fish: syntax colours in slots; no greeting, no autosuggestions (they would
// leak command history into the shots).
export function fishConfig() {
	return `# Generated by screens/runner/theme.mjs: fish colours as ANSI slots.
set -g fish_greeting
set -g fish_autosuggestion_enabled 0
set -g fish_color_normal normal
set -g fish_color_command cyan
set -g fish_color_keyword magenta
set -g fish_color_param normal
set -g fish_color_option brblack
set -g fish_color_quote green
set -g fish_color_redirection yellow
set -g fish_color_end yellow
set -g fish_color_error red
set -g fish_color_comment brblack
set -g fish_color_operator yellow
set -g fish_color_escape yellow
set -g fish_color_autosuggestion brblack
set -g fish_color_valid_path --underline
set -g fish_pager_color_prefix yellow
set -g fish_pager_color_completion normal
set -g fish_pager_color_description brblack
starship init fish | source
`;
}

// starship: where you are, the git branch, how long the last command took,
// and the prompt character. Nothing else.
export function starshipConfig() {
	return `# Generated by screens/runner/theme.mjs: the prompt in ANSI slots.
add_newline = true
format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "on [$branch]($style) "
style = "bold purple"

[git_status]
style = "yellow"

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bright-black"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[username]
disabled = true

[hostname]
disabled = true
`;
}

export function installShellConfig(home = process.env.HOME ?? '/root') {
	const fishDir = path.join(home, '.config/fish/conf.d');
	fs.mkdirSync(fishDir, { recursive: true });
	// fish's first interactive start generates man-page completions with a
	// background python3. Where fish is PID 1 (an isolated story) nothing reaps
	// it, and poptop lists the zombie. Its directory existing tells fish not to
	// (fish 4 looks in the cache dir: __fish_config_interactive.fish).
	fs.mkdirSync(path.join(home, '.cache/fish/generated_completions'), { recursive: true });
	fs.writeFileSync(path.join(fishDir, 'devtools.fish'), fishConfig());
	fs.writeFileSync(path.join(home, '.config/starship.toml'), starshipConfig());
}
